"""Dictionary maps dept code to dept name. Not sure if I'll use it."""

dept_names = {"acen": "Academic English",
              "amst": "American Studies",
              "anth": "Anthropology",
              "aplx": "Applied Linguistics",
              "ams": "Applied Math and Statistics",
              "arab": "Arabic",
              "art": "Art",
              "artg": "Art&Des:Games&PlayableMedia",
              "astr": "Astronomy and Astrophysics",
              "bioc": "Biochemistry and Molecular Bio",
              "biol": "Biology: Molecular Cell & Dev",
              "bioe": "Biology:Ecology & Evolutionary",
              "bme": "Biomolecular Engineering",
              "chem": "Chemistry and Biochemistry",
              "chin": "Chinese",
              "clei": "College Eight",
              "clni": "College Nine",
              "clte": "College Ten",
              "cmmu": "Community Studies",
              "cmpm": "Computational Media",
              "cmpe": "Computer Engineering",
              "cmps": "Computer Science",
              "cowl": "Cowell College",
              "ltcr": "Creative Writing",
              "cres": "Critical Race & Ethnic Studies",
              "crwn": "Crown College",
              "danm": "Digital Arts and New Media",
              "eart": "Earth Sciences",
              "econ": "Economics",
              "educ": "Education",
              "ee": "Electrical Engineering",
              "engr": "Engineering",
              "ltel": "English-Language Literatures",
              "envs": "Environmental Studies",
              "etox": "Environmental Toxicology",
              "fmst": "Feminist Studies",
              "film": "Film and Digital Media",
              "fren": "French",
              "ltfr": "French Literature",
              "game": "Games and Playable Media",
              "germ": "German",
              "ltge": "German Literature",
              "gree": "Greek",
              "ltgr": "Greek Literature",
              "hebr": "Hebrew",
              "hndi": "Hindi",
              "his": "History",
              "havc": "History of Art&Visual Culture",
              "hisc": "History of Consciousness",
              "humn": "Humanities",
              "ism": "Information Systems Management",
              "ital": "Italian",
              "ltit": "Italian Literature",
              "japn": "Japanese",
              "jwst": "Jewish Studies",
              "krsg": "Kresge College",
              "laad": "Languages",
              "latn": "Latin",
              "lals": "Latin American&Latino Studies",
              "ltin": "Latin Literature",
              "lgst": "Legal Studies",
              "ling": "Linguistics",
              "lit": "Literature",
              "math": "Mathematics",
              "merr": "Merrill College",
              "metx": "Microbiol & Environ Toxicology",
              "ltmo": "Modern Literary Studies",
              "musc": "Music",
              "oaks": "Oakes College",
              "ocea": "Ocean Sciences",
              "phil": "Philosophy",
              "phye": "Physical Education",
              "phys": "Physics",
              "poli": "Politics",
              "prtr": "Porter College",
              "port": "Portuguese",
              "ltpr": "Pre & Early Modern Literature",
              "psyc": "Psychology",
              "punj": "Punjabi",
              "russ": "Russian",
              "scic": "Science Communication",
              "socd": "Social Documentation",
              "socs": "Social Sciences",
              "socy": "Sociology",
              "span": "Spanish",
              "sphs": "Spanish for Heritage Speakers",
              "spss": "Spanish for Spanish Speakers",
              "ltsp": "Spanish/Latin Amer/Latino Lit",
              "stev": "Stevenson College",
              "tim": "Technology & Info Management",
              "thea": "Theater Arts",
              "ucdc": "UCDC",
              "wmst": "Women's Studies",
              "ltwl": "World Lit & Cultural Studies",
              "writ": "Writing",
              "yidd": "Yiddish",
              }
